[General]
Daemon=0

[Log]
# Logging levels, 0=No logging
DisplayLevel=1
MQTTLevel=1

[MQTT]
Host=127.0.0.1
Port=1883
Auth=0
Username=mmdvm
Password=mmdvm
Keepalive=60
Name=modem

[Modem]
# Valid values are "uart" or "udp"
Protocol=uart
# The port and speed used for a UART connection
UARTPort=\\.\COM9
# UARTPort=/dev/ttyACM0
# UARTPort=/dev/ttyAMA0
UARTSpeed=2500000
# IP parameters for UDP connection
RemoteAddress=127.0.0.1
RemotePort=3334
LocalAddress=127.0.0.1
LocalPort=3335
Trace=0

[MMDVM Host]
HostAddress=127.0.0.1
HostPort=3335
LocalAddress=127.0.0.1
LocalPort=3334
Trace=0
