[General]
Daemon=0

[Log]
# Logging levels, 0=No logging
DisplayLevel=1
FileLevel=1
FilePath=.
FileRoot=MMDVM-PC
FileRotate=1

[Modem]
Port=\\.\COM6
# Port=/dev/ttyACM0
# Port=/dev/ttyAMA0
Speed=921600
Trace=0

[MMDVM Host]
HostAddress=127.0.0.1
HostPort=3335
LocalAddress=127.0.0.1
LocalPort=3334
Trace=0
