[General]
Daemon=0

[Log]
# Logging levels, 0=No logging
DisplayLevel=1
MQTTLevel=1

[MQTT]
Host=127.0.0.1
Port=1883
Auth=0
Username=mmdvm
Password=mmdvm
Keepalive=60
Name=modem

[Modem]
#Type=plutosdr             # driver name, supports pluto, limesdr or sx(default)
#URI=ip:pluto.local        # soapy uri, Use usb:1.1.5 for plutosdr; use serial=xxxxx for limesdr
Trace=0

[MMDVM Host]
HostAddress=127.0.0.1
HostPort=3335
LocalAddress=127.0.0.1
LocalPort=3334
Trace=0
