[General]
Daemon=0

[Log]
# Logging levels, 0=No logging
FileLevel=1
FilePath=/tmp
FileRoot=MMDVM-IQ
DisplayLevel=1
MQTTLevel=1

[MQTT]
Host=127.0.0.1
Port=1883
Auth=0
Username=mmdvm
Password=mmdvm
Keepalive=60
Name=mmdvm-iq

[Modem]
# To compatible with old host protocol, use version 1
Version=2

# To support multi channels, use 2 ~ 4
# The modem listen port auto increases
ActiveChannels=4
DisableMulti=1

# For the SXceiver
# Type=sx
# RxGain=50
# TxGain=30

# For the Pluto SDR
Type=plutosdr
RxGain=30
TxGain=89
# RxAntenna=A_BALANCED
# TxAntenna=A
URI=ip:pluto.local        # Soapy URI, use usb:1.1.5 for plutosdr

# For the LibreSDR (uses the SoapyPluto driver with a LibreSDR-specific profile)
# Type=libresdr
# RxGain=20
# TxGain=70
# URI=ip:192.168.2.10

# For the Lime SDR
# Type=limesdr
# RxGain=30
# TxGain=60
# RxAntenna=LNAH
# TxAntenna=BAND1

# For the LimeSDR-mini or LimeNET-micro v1
# Type=limemini
# RxGain=30
# TxGain=64
# URI="serial=xxxx"

# For the LimePSB RPCM
# Type=limepsb
# RxGain=30
# TxGain=52
# URI="serial=xxxx"

# For the Ettus USRP and clones
# Type=usrp
# RxGain=30
# TxGain=89
# URI="serial=xxxx"

Trace=0

[MMDVM Host]
HostAddress=127.0.0.1
HostPort=33350
LocalAddress=127.0.0.1
LocalPort=33340
Trace=0

[MMDVM Multi]
Enabled=0
MultiModemAddress=127.0.0.1
MultiModemPort=48200
LocalAddress=127.0.0.1
LocalPort=48100
