[General]
Daemon=0

[Log]
# Logging levels, 0=No logging
DisplayLevel=1
MQTTLevel=1

[MQTT]
Host=127.0.0.1
Port=1883
Auth=0
Username=mmdvm
Password=mmdvm
Keepalive=60
Name=mmdvm-iq

[Modem]
# For the SXceiver
Type=sx
RxGain=50
TxGain=30

# For the Pluto SDR
# Type=plutosdr
# RxGain=30
# TxGain=89
# URI=ip:pluto.local        # Soapy URI, use usb:1.1.5 for plutosdr

# For the Lime SDR
# Type=limesdr
# RxGain=30
# TxGain=60

# For the LimeSDR-mini or LimeNET-micro v1
# Type=limemini
# RxGain=30
# TxGain=64
# URI="serial=xxxx"

# For the Ettus USRP and clones
# Type=usrp
# RxGain=30
# TxGain=89
# URI="serial=xxxx"

Trace=0

[MMDVM Host]
HostAddress=127.0.0.1
HostPort=3335
LocalAddress=127.0.0.1
LocalPort=3334
Trace=0

[MMDVM Multi]
Enabled=0
MultiModemAddress=127.0.0.1
MultiModemPort=48200
LocalAddress=127.0.0.1
LocalPort=48100

